## numpy

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [4,5,7]])
a

array([list([1, 2]), list([4, 5, 7])], dtype=object)

In [3]:
a = np.arange(1,2,0.1)
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [4]:
# 生成等差数列
a = np.linspace(0, 1, 12)
a

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [6]:
# 生成等比数列
a = np.logspace(0, 2, 5)
a

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])